### ISSUE TITLE
When updating ceil, floor and model the bubble label is not refreshed

### ISSUE THREAD

**Issue by Martin-Wegner** [rzajac/angularjs-slider#156] opened 2015-10-20 15:53 UTC
When updating ceil, floor and model the bubble label is not refreshed.

Please see my example here:
https://jsfiddle.net/zfee1pxb/2/

**Comment by ValentinH** [comment] 2015-10-20 16:45
Well spotted! It was hard to understand the issue but I found the cause.
Once more, it is due to this line: https://github.com/rzajac/angularjs-slider/blob/master/src/rzslider.js#L823 .

I already got issue with this line and in my project, I removed it. I don't know the point of it so I'm removing it. It might have been for optimization but it leads to several bugs.

**Comment by ValentinH** [comment] 2015-10-20 16:47
Should be fixed now.

**Closed** 2015-10-20 16:47 UTC
