### ISSUE TITLE
Is it possible to lock range?

### ISSUE THREAD

**Issue by yelnar** [rzajac/angularjs-slider#199] opened 2015-12-10 23:09 UTC
Whenever I change the range its length would stay the same. This would be awesome.

**Comment by ValentinH** [comment] 2015-12-11 05:50
Is this similar as #196 ?

**Comment by yelnar** [comment] 2015-12-12 14:28
Yes it is. Now I use `onEnd` option to implement it, but it is little bit dirty so I think it would be awesome to have this feature natively.

**Comment by ValentinH** [comment] 2015-12-14 09:12
It should not be very hard to implement it. It's the next thing on my todo list ;) 

I'm closing this one as duplicate of #196 .

**Closed by ValentinH** 2015-12-14 09:12 UTC
